# Generated by Django 6.1.1 on 2026-10-03 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subject", models.CharField(max_length=100)),
                ("grade_level", models.CharField(max_length=50)),
                ("term", models.CharField(max_length=50)),
                ("academic_year", models.CharField(max_length=10)),
                ("pdf_file", models.FileField(upload_to="exams/")),
                ("uploaded_by", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="balance",
        ),
        migrations.AddField(
            model_name="schoolclass",
            name="zoom_meeting_id",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="schoolclass",
            name="zoom_passcode",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="schoolclass",
            name="zoom_start_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("mpesa", "M-Pesa"),
                            ("card", "Card"),
                            ("bank", "Bank Transfer"),
                        ],
                        default="mpesa",
                        max_length=20,
                    ),
                ),
                ("reference", models.CharField(max_length=60, unique=True)),
                ("status", models.CharField(default="completed", max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="school.invoice",
                    ),
                ),
            ],
        ),
    ]
