# Generated by Django 6.1.1 on 2026-10-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0002_exam_remove_invoice_balance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("mpesa", "M-Pesa"),
                    ("paypal", "PayPal"),
                    ("visa", "Visa"),
                    ("card", "Card"),
                    ("bank", "Bank Transfer"),
                ],
                default="mpesa",
                max_length=20,
            ),
        ),
    ]
