# Generated by Django 6.1.2 on 2026-10-09 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0004_schoolclass_lesson_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="PracticalAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "practical",
                    models.CharField(
                        default="Physics: investigating a resistor", max_length=100
                    ),
                ),
                ("session_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("present", "Present"), ("absent", "Absent")],
                        max_length=10,
                    ),
                ),
                ("marked_at", models.DateTimeField(auto_now=True)),
                (
                    "marked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marked_practical_attendance",
                        to="school.user",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practical_attendance",
                        to="school.user",
                    ),
                ),
            ],
            options={
                "ordering": ("student__last_name", "student__first_name"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "practical", "session_date"),
                        name="unique_student_practical_attendance_per_day",
                    )
                ],
            },
        ),
    ]
