# Generated by Django 6.1.2 on 2026-10-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0005_practicalattendance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schoolclass",
            name="zoom_meeting_id",
        ),
        migrations.RemoveField(
            model_name="schoolclass",
            name="zoom_passcode",
        ),
        migrations.RemoveField(
            model_name="schoolclass",
            name="zoom_start_url",
        ),
        migrations.AddField(
            model_name="schoolclass",
            name="google_calendar_event_id",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
